import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: "class",
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./data/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  safelist: [
    "col-span-1",
    "col-span-2",
    "col-span-3",
    "col-span-4",
    "col-span-6",
    "col-span-8",
    "col-span-12",
    "md:col-span-3",
    "md:col-span-4",
    "md:col-span-6",
    "md:col-span-12",
    "lg:col-span-3",
    "lg:col-span-4",
    "lg:col-span-6",
    "lg:col-span-8",
    "lg:col-span-12",
  ],
  theme: {
    extend: {
      colors: {
        "bg-base": "#0A0E0C",
        "bg-gradient-start": "#101B14",
        "surface": "#101412",
        "surface-dim": "#101412",
        "surface-bright": "#363a38",
        "surface-container-lowest": "#0b0f0d",
        "surface-container-low": "#181c1a",
        "surface-container": "#1c201e",
        "surface-container-high": "#272b28",
        "surface-container-highest": "#323633",
        "on-surface": "#e0e3df",
        "on-surface-variant": "#bacbb9",
        "primary": "#f5fff2",
        "on-primary": "#003918",
        "primary-container": "#39ff88",
        "on-primary-container": "#007236",
        "accent-fallback": "#5ED9A0",
        "secondary": "#b5ccbd",
        "on-secondary": "#21352a",
        "secondary-container": "#394e42",
        "on-secondary-container": "#a7beaf",
        "text-primary": "#E8F5EC",
        "text-muted": "#7C9284",
        "glass-fill": "rgba(200, 255, 220, 0.05)",
        "glass-border": "rgba(200, 255, 220, 0.14)",
        "error": "#ffb4ab",
        "error-container": "#93000a",
      },
      fontFamily: {
        sans: ["var(--font-ibm-plex-sans)", "system-ui", "sans-serif"],
        mono: ["var(--font-ibm-plex-mono)", "Courier Prime", "monospace"],
        "code-block": ["Courier Prime", "var(--font-ibm-plex-mono)", "monospace"],
        "code-chip": ["Courier Prime", "var(--font-ibm-plex-mono)", "monospace"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        full: "9999px",
      },
      boxShadow: {
        glass: "0 8px 28px rgba(0, 0, 0, 0.45)",
        "terminal-glow": "0 0 20px rgba(57, 255, 136, 0.25)",
        "terminal-glow-lg": "0 0 35px rgba(57, 255, 136, 0.35)",
      },
      animation: {
        "pulse-slow": "pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite",
        "ping-slow": "ping 2s cubic-bezier(0, 0, 0.2, 1) infinite",
        "cursor-blink": "blink 1s step-start infinite",
      },
      keyframes: {
        blink: {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0" },
        },
      },
    },
  },
  plugins: [],
};

export default config;
